name: LOUP-GAROUS
version: 0.4
author: Aiidor
main: fr.aiidor.LGUHC
commands:
  config:
    description: Commande Host/Orga
  lg:
    description: Permet d'effectuer les commandes joueurs du LG
  spec:
    description: Permet au spectateur d'obtenir des informations
  
