name: LOUP-GAROUS
version: 0.3
author: B_Goodes
main: fr.aiidor.LGUHC
commands:
  config:
    description: Permet de forcer une action
  lg:
    description: Permet d'effectuer les commandes joueurs du LG
  spec:
    description: Permet au spectateur d'obtenir des informations
  
