name: LOUP-GAROUS
version: 0.2
author: Aiidor
main: fr.aiidor.LGUHC
commands:
  bypass:
    description: Permet de forcer une action
    permission: force.use
  lg:
    description: Permet d'effectuer les commandes joueurs du LG
  test:
    descrition: test